version: '2.4'

services:
  python:
    build:
      context: ../
    volumes:
      - ../:/usr/src/binance/
    working_dir: /usr/src/binance/
    environment:
      TZ: Asia/Krasnoyarsk
    command: python /usr/src/binance/main.py
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
